export const users = [
  {
    _id: "2476135976",
    first_name: "John",
    last_name: "Doe",
    email: "john@smith.com",
    phone_number: "01983738764",
    username: "john",
    role: "admin",
    password: "nt39287562387",
    confirm_password: "string",
    father_name: "Smith",
    nid_number: 2713457365,
    birth_date: new Date(),
    gender: "male",
    marital_status: "married",
    marriage_date: new Date(),
    permanent_address: "magura, benerpota, satkhira",
    current_address: "magura, benerpota, satkhira",
    bank_name: "AB Bank",
    branch_name: "satkhira",
    account_name: "John Smith",
    account_number: 827254108,
    swift_code: 318946,
    routing_number: 3847,
    mobile: "0341058976013897",
    primary_payment_options: "bkash",
    bkash: 8734106876,
  },
  {
    _id: "3256798312",
    first_name: "Alice",
    last_name: "Johnson",
    email: "alice@johnson.com",
    phone_number: "01726384752",
    username: "alice",
    role: "user",
    password: "jt9257364821",
    confirm_password: "string",
    father_name: "Johnson",
    nid_number: 3647251892,
    birth_date: new Date(),
    gender: "female",
    marital_status: "single",
    marriage_date: null,
    permanent_address: "123 Main St, Anytown, USA",
    current_address: "123 Main St, Anytown, USA",
    bank_name: "XYZ Bank",
    branch_name: "Anytown",
    account_name: "Alice Johnson",
    account_number: 983746523,
    swift_code: 537812,
    routing_number: 9283,
    mobile: "0123456789012345",
    primary_payment_options: "roket",
    roket: "02387514876",
  },
  {
    _id: "0987234561",
    first_name: "Michael",
    last_name: "Brown",
    email: "michael@brown.com",
    phone_number: "01654823791",
    username: "mike",
    role: "user",
    password: "mb783956102",
    confirm_password: "string",
    father_name: "Brown",
    nid_number: 5982637451,
    birth_date: new Date(),
    gender: "male",
    marital_status: "divorced",
    marriage_date: new Date("2008-05-15"),
    permanent_address: "456 Elm St, Springfield, USA",
    current_address: "456 Elm St, Springfield, USA",
    bank_name: "ABC Bank",
    branch_name: "Springfield",
    account_name: "Michael Brown",
    account_number: 735914672,
    swift_code: 284651,
    routing_number: 7289,
    mobile: "0789564123789564",
    primary_payment_options: "stripe",
    stripe: "mikebrown@example.com",
  },
  {
    _id: "7654321987",
    first_name: "Emily",
    last_name: "Davis",
    email: "emily@davis.com",
    phone_number: "01573264829",
    username: "emily",
    role: "user",
    password: "ed638571924",
    confirm_password: "string",
    father_name: "Davis",
    nid_number: 1785634920,
    birth_date: new Date(),
    gender: "female",
    marital_status: "married",
    marriage_date: new Date("2016-10-20"),
    permanent_address: "789 Oak St, Oakville, USA",
    current_address: "789 Oak St, Oakville, USA",
    bank_name: "DEF Bank",
    branch_name: "Oakville",
    account_name: "Emily Davis",
    account_number: 124689375,
    swift_code: 975318,
    routing_number: 9834,
    mobile: "0956743120987432",
    primary_payment_options: "nogod",
    nogod: "01847156087",
  },
];

export const projects = [
  {
    _id: "38475698276",
    customer: "Abul Kalam",
    duration: "50 minutes",
    location: "Dhaka",
    project_title: "Ecommerce",
    project_value: "1000",
  },
  {
    _id: "38475698276",
    customer: "Abul karim",
    duration: "40 minutes",
    location: "Rajshahi",
    project_title: "Web Development",
    project_value: "2000",
  },
  {
    _id: "38475698276",
    customer: "Md Hasibul",
    duration: "30 minutes",
    location: "Khulna",
    project_title: "App  development",
    project_value: "1500",
  },
];


export const customers = [
  {
    _id: 1,
    first_name: "Fatima",
    last_name: "Pollard",
    email: "kota@mailinator.com",
    phone_number: "+1 (492) 223-7109",
    company_name: "Newton Pearson Plc",
    father_name: "Laith Monroe",
    nid_number: "738",
    birth_date: "2005-07-02",
    gender: "male",
    bin: "Recusandae Placeat",
    advance_balance: "700",
    permanent_address: "Adipisicing similiqu",
    current_address: "Debitis aut laborum",
  },
  {
    _id: 2,
    first_name: "Sophia",
    last_name: "Watkins",
    email: "sophia@mailinator.com",
    phone_number: "+1 (123) 456-7890",
    company_name: "Smith & Co.",
    father_name: "John Watkins",
    nid_number: "123",
    birth_date: "1998-05-15",
    gender: "female",
    bin: "Lorem Ipsum",
    advance_balance: "500",
    permanent_address: "123 Main St",
    current_address: "456 Elm St",
  },
  {
    _id: 3,
    first_name: "Elijah",
    last_name: "Gonzalez",
    email: "elijah@mailinator.com",
    phone_number: "+1 (987) 654-3210",
    company_name: "Gonzalez Enterprises",
    father_name: "Carlos Gonzalez",
    nid_number: "567",
    birth_date: "1990-12-20",
    gender: "male",
    bin: "Dolor Sit Amet",
    advance_balance: "1000",
    permanent_address: "789 Oak Ave",
    current_address: "567 Pine St",
  },
  {
    _id: 4,
    first_name: "Ava",
    last_name: "Lopez",
    email: "ava@mailinator.com",
    phone_number: "+1 (555) 555-5555",
    company_name: "Lopez Corporation",
    father_name: "Jose Lopez",
    nid_number: "987",
    birth_date: "2002-03-10",
    gender: "female",
    bin: "Consectetur Adipisicing",
    advance_balance: "900",
    permanent_address: "111 Maple St",
    current_address: "222 Cherry St",
  },
  {
    _id: 5,
    first_name: "Noah",
    last_name: "Nguyen",
    email: "noah@mailinator.com",
    phone_number: "+1 (999) 999-9999",
    company_name: "Nguyen & Sons",
    father_name: "Tuan Nguyen",
    nid_number: "456",
    birth_date: "2008-09-25",
    gender: "male",
    bin: "Eligendi Voluptatem",
    advance_balance: "300",
    permanent_address: "333 Oak St",
    current_address: "444 Pine St",
  },
];

export const tasks = [
  {
    _id: "1",
    customer: "ABC Corp",
    project: "Website Redesign",
    task: "Design landing page",
    task_date: new Date("2024-03-20T08:00:00Z"),
    task_alert_date: new Date("2024-03-19T08:00:00Z"),
    alert_type: "Email",
    note: "This task involves creating the visual design for the landing page.",
  },
  {
    _id: "2",
    customer: "XYZ Corp",
    project: "App Development",
    task: "Implement user authentication",
    task_date: new Date("2024-03-25T10:00:00Z"),
    task_alert_date: new Date("2024-03-24T10:00:00Z"),
    alert_type: "SMS",
    note: "This task involves setting up user authentication functionality using OAuth.",
  },
  {
    _id: "3",
    customer: "LMN Corp",
    project: "Marketing Campaign",
    task: "Create social media graphics",
    task_date: new Date("2024-03-22T12:00:00Z"),
    task_alert_date: new Date("2024-03-21T12:00:00Z"),
    alert_type: "Popup",
    note: "This task involves designing engaging graphics for social media platforms.",
  },
  {
    _id: "4",
    customer: "PQR Corp",
    project: "Product Launch",
    task: "Finalize product packaging",
    task_date: new Date("2024-03-18T15:00:00Z"),
    task_alert_date: new Date("2024-03-17T15:00:00Z"),
    alert_type: "Notification",
    note: "This task involves making the final decisions on product packaging design.",
  },
];
